import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("E:/foss_backup/backup.status.csv", sep='|', header=0,  encoding="ISO-8859-1" )
# print(df.columns)
# print(df.head(20))

df_year_month = df[df['year'] >= 2000]
df_year_month= df_year_month.groupby(['year'])['row_id'].count()
# print(type(df_year_month))
# print(df_year_month)

#Lets scale the value
#df_year_month_scaled = df_year_month.apply( lambda x : x - df_year_month.min())/(df_year_month.max() - df_year_month.min())
#ax = df_year_month_scaled.plot(x = 'year', y = 'month' , title='Number of files generated by Year-Month', markersize='10', marker = '.')

df_year_month.plot(x = 'Year-Month', y = 'Files Count' , title='Number of photos and videos created by Year', markersize='10', marker = '.')
plt.show()
# print(df_year_month)






